import { Dimensions, StyleSheet } from "react-native";
import { DESIGN_SYSTEM } from "../core/theme/designSystem";

const {width} = Dimensions.get('window');
const CARD_WIDTH = width * 0.85;
const CARD_HEIGHT = 165;

export const createLevelSelectionStyles = (colors: any) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors?.background?.primary || '#0A0A0F',
    },
    backgroundCurve: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 0,
    },
    header: {
      paddingHorizontal: DESIGN_SYSTEM.spacing.xl,
      paddingTop: DESIGN_SYSTEM.spacing.xl,
      paddingBottom: DESIGN_SYSTEM.spacing.lg,
      alignItems: 'center',
      zIndex: 2,
    },
    headerTop: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: DESIGN_SYSTEM.spacing.md,
    },
    headerTitle: {
      flex: 1,
    },
    mainTitle: {
      fontSize: DESIGN_SYSTEM.typography.fontSizes.md,
      fontWeight: 'bold',
      color: colors?.text?.primary || '#FFFFFF',
      fontFamily: 'Nunito-Bold',
      textAlign: 'center',
    },
    subtitle: {
      fontSize: 16,
      color: colors?.text?.secondary || '#A0A0B0',
      fontFamily: 'Nunito-Medium',
      textAlign: 'center',
      marginTop: 4,
    },
    headerButtons: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    puzzlePacksButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: 'rgba(139, 92, 246, 0.8)',
      borderWidth: 2,
      borderColor: 'rgba(139, 92, 246, 0.4)',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: DESIGN_SYSTEM.spacing.sm,
      ...DESIGN_SYSTEM.elevation.medium,
    },
    puzzlePacksButtonText: {
      fontSize: 22,
      color: colors?.text?.inverse || '#FFFFFF',
    },
    menuButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
    backgroundColor: colors?.background?.surface || '#f1f5f9',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.2)',
      justifyContent: 'center',
      alignItems: 'center',
      ...DESIGN_SYSTEM.elevation.subtle,
    },
    menuButtonText: {
      fontSize: 20,
      color: colors?.text?.primary || '#161618',
      fontWeight: 'bold',
    },
    scrollView: {
      flex: 1,
      zIndex: 1,
    },
    scrollContent: {
      paddingHorizontal: DESIGN_SYSTEM.spacing.lg,
      paddingBottom: DESIGN_SYSTEM.spacing.xxxl,
      paddingTop: DESIGN_SYSTEM.spacing.lg,
    },
    levelCardContainer: {
      marginBottom: DESIGN_SYSTEM.spacing.xl,
      alignItems: 'center',
    },
    levelCard: {
      width: CARD_WIDTH,
      height: CARD_HEIGHT,
      borderRadius: DESIGN_SYSTEM.borderRadius.xl,
      overflow: 'visible',
      position: 'relative',
      ...DESIGN_SYSTEM.elevation.medium,
    },
    lockedCard: {
      opacity: 0.6,
    },
    cardGradient: {
      flex: 1,
      borderRadius: DESIGN_SYSTEM.borderRadius.xl,
      padding: DESIGN_SYSTEM.spacing.lg,
      justifyContent: 'space-between',
      borderWidth: 2,
      borderColor: 'rgba(139, 92, 246, 0.3)',
    },
    completedCardGradient: {
      borderColor: 'rgba(16, 185, 129, 0.5)',
      shadowColor: '#10B981',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 8,
    },
    cardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    levelInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    levelIcon: {
      fontSize: 36,
      marginRight: DESIGN_SYSTEM.spacing.md,
    },
    levelDetails: {
      flex: 1,
    },
    levelName: {
      fontSize: DESIGN_SYSTEM.typography.fontSizes.xl,
      fontWeight: 'bold',
      color: colors?.text?.inverse || '#FFFFFF',
      fontFamily: 'Nunito-Bold',
    },
    levelDifficulty: {
      fontSize: DESIGN_SYSTEM.typography.fontSizes.md,
      color: colors?.text?.inverse || '#FFFFFF',
      fontFamily: 'Nunito-Medium',
      opacity: 0.9,
      marginTop: DESIGN_SYSTEM.spacing.xs,
    },
    levelMeta: {
      alignItems: 'flex-end',
    },
    levelNumber: {
      fontSize: 24,
      fontWeight: 'bold',
      color: colors?.text?.inverse || '#FFFFFF',
      fontFamily: 'Nunito-Bold',
      opacity: 0.8,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 12,
      overflow: 'hidden',
    },
    starsContainer: {
      flexDirection: 'row',
      marginTop: DESIGN_SYSTEM.spacing.xs,
      backgroundColor: 'rgba(0, 0, 0, 0.2)',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    star: {
      fontSize: 14,
      marginHorizontal: 1,
    },
    filledStar: {
      color: '#FFD700',
    },
    emptyStar: {
      color: 'rgba(255, 255, 255, 0.3)',
    },
    levelDescription: {
      fontSize: DESIGN_SYSTEM.typography.fontSizes.sm,
      color: colors?.text?.inverse || '#FFFFFF',
      fontFamily: 'Nunito-Regular',
      opacity: 0.9,
      marginTop: DESIGN_SYSTEM.spacing.sm,
    },
    unlockInfo: {
      marginTop: DESIGN_SYSTEM.spacing.sm,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 8,
    },
    unlockText: {
      fontSize: DESIGN_SYSTEM.typography.fontSizes.sm,
      color: colors?.text?.inverse || '#FFFFFF',
      fontFamily: 'Nunito-SemiBold',
      opacity: 0.9,
    },
    bestTime: {
      fontSize: DESIGN_SYSTEM.typography.fontSizes.sm,
      color: colors?.text?.inverse || '#FFFFFF',
      fontFamily: 'Nunito-Medium',
      opacity: 0.8,
      textAlign: 'right',
      marginVertical: -DESIGN_SYSTEM.spacing.sm,
    },
    completedBadge: {
      position: 'absolute',
      top: -8,
      right: -8,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: '#10B981',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#10B981',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.5,
      shadowRadius: 4,
      elevation: 6,
    },
    completedBadgeText: {
      fontSize: 16,
      color: '#FFFFFF',
      fontWeight: 'bold',
    },
    lockedBadge: {
      position: 'absolute',
      top: -8,
      right: -8,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    lockedBadgeText: {
      fontSize: 16,
      color: '#FFFFFF',
    },
    progressBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 4,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      borderBottomLeftRadius: DESIGN_SYSTEM.borderRadius.xl,
      borderBottomRightRadius: DESIGN_SYSTEM.borderRadius.xl,
    },
    progressFill: {
      height: '100%',
      backgroundColor: '#10B981',
      borderBottomLeftRadius: DESIGN_SYSTEM.borderRadius.xl,
    },
    footer: {
      alignItems: 'center',
      paddingTop: DESIGN_SYSTEM.spacing.xl,
      paddingBottom: DESIGN_SYSTEM.spacing.lg,
    },
    footerText: {
      fontSize: DESIGN_SYSTEM.typography.fontSizes.md,
      color: colors?.text?.secondary || '#A0A0B0',
      fontFamily: 'Nunito-Medium',
      opacity: 0.7,
      textAlign: 'center',
    },
    puzzlePacksCard: {
      width: CARD_WIDTH,
      height: 150,
      borderRadius: DESIGN_SYSTEM.borderRadius.xl,
      marginBottom: DESIGN_SYSTEM.spacing.xl,
      alignSelf: 'center',
      overflow: 'visible',
      ...DESIGN_SYSTEM.elevation.medium,
    },
    puzzlePacksGradient: {
      flex: 1,
      borderRadius: DESIGN_SYSTEM.borderRadius.xl,
      padding: DESIGN_SYSTEM.spacing.lg,
      justifyContent: 'space-between',
      borderWidth: 2,
      borderColor: 'rgba(139, 92, 246, 0.4)',
      shadowColor: '#8B5CF6',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 8,

    },
    puzzlePacksHeader: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    puzzlePacksIcon: {
      fontSize: 28,
      marginRight: DESIGN_SYSTEM.spacing.md,
    },
    puzzlePacksInfo: {
      flex: 1,
    },
    puzzlePacksTitle: {
      fontSize: DESIGN_SYSTEM.typography.fontSizes.xl,
      fontWeight: 'bold',
      color: colors?.text?.inverse || '#FFFFFF',
      fontFamily: 'Nunito-Bold',
    },
    puzzlePacksSubtitle: {
      fontSize: DESIGN_SYSTEM.typography.fontSizes.md,
      color: colors?.text?.inverse || '#FFFFFF',
      fontFamily: 'Nunito-Medium',
      opacity: 0.9,
      marginTop: 2,
    },
    puzzlePacksArrow: {
      fontSize: 28,
      color: colors?.text?.inverse || '#FFFFFF',
      fontWeight: 'bold',
    },
    puzzlePacksDescription: {
      fontSize: DESIGN_SYSTEM.typography.fontSizes.sm,
      color: colors?.text?.inverse || '#FFFFFF',
      fontFamily: 'Nunito-Regular',
      opacity: 0.8,
      marginTop: DESIGN_SYSTEM.spacing.sm,
    },
    replayContainer: {
      position: 'absolute',
      bottom: 8,
      left: 8,
      backgroundColor: 'rgba(255, 255, 255, 0.9)',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: DESIGN_SYSTEM.borderRadius.sm,
      borderWidth: 1,
      borderColor: 'rgba(139, 92, 246, 0.3)',
    },
    replayText: {
      fontSize: 11,
      color: colors?.interactive?.primary || '#8B5CF6',
      fontWeight: '600',
    },
    loadingContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: DESIGN_SYSTEM.spacing.xl * 2,
    },
    loadingText: {
      fontSize: 18,
      color: colors?.text?.inverse || '#FFFFFF',
      textAlign: 'center',
      fontWeight: '500',
      fontFamily: 'Nunito-Medium',
    },
  });
};

// Legacy export for backward compatibility  
export const levelSelectionStyles = createLevelSelectionStyles({} as any);